-- Create Database
CREATE DATABASE IF NOT EXISTS car_rental;
USE car_rental;

-- 1. Users Table
CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user'
);

-- 2. Cars Table
CREATE TABLE IF NOT EXISTS cars (
    car_id INT AUTO_INCREMENT PRIMARY KEY,
    car_name VARCHAR(100) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(20) NOT NULL,
    category VARCHAR(50) NOT NULL,
    fuel_type VARCHAR(50) NOT NULL,
    transmission VARCHAR(50) NOT NULL,
    price_per_day DOUBLE NOT NULL,
    availability VARCHAR(20) NOT NULL DEFAULT 'Available',
    image VARCHAR(255) NOT NULL
);

-- 3. Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
    booking_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    car_id INT NOT NULL,
    pickup_date VARCHAR(50) NOT NULL,
    return_date VARCHAR(50) NOT NULL,
    total_amount DOUBLE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Pending',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (car_id) REFERENCES cars(car_id) ON DELETE CASCADE
);

-- 4. Payments Table
CREATE TABLE IF NOT EXISTS payments (
    payment_id INT AUTO_INCREMENT PRIMARY KEY,
    booking_id INT NOT NULL,
    transaction_id VARCHAR(100) NOT NULL UNIQUE,
    amount DOUBLE NOT NULL,
    payment_status VARCHAR(50) NOT NULL DEFAULT 'Completed',
    FOREIGN KEY (booking_id) REFERENCES bookings(booking_id) ON DELETE CASCADE
);

-- Insert Demo Cars (120 Distinct Premium/SUV/Electric/Budget Cars)
INSERT INTO cars (car_name, brand, model, category, fuel_type, transmission, price_per_day, availability, image) VALUES
('C-Class C200', 'Mercedes-Benz', '2024', 'Premium', 'Petrol', 'Automatic', 5000.0, 'Available', 'mercedes.jpg'),
('E-Class E220d', 'Mercedes-Benz', '2024', 'Premium', 'Diesel', 'Automatic', 6500.0, 'Available', 'mercedes.jpg'),
('S-Class S350d', 'Mercedes-Benz', '2024', 'Premium', 'Diesel', 'Automatic', 8500.0, 'Available', 'mercedes.jpg'),
('GLC 220d', 'Mercedes-Benz', '2023', 'Premium', 'Diesel', 'Automatic', 5500.0, 'Available', 'mercedes.jpg'),
('GLE 300d', 'Mercedes-Benz', '2023', 'Premium', 'Diesel', 'Automatic', 7000.0, 'Available', 'mercedes.jpg'),
('GLS 400d', 'Mercedes-Benz', '2024', 'Premium', 'Diesel', 'Automatic', 9000.0, 'Available', 'mercedes.jpg'),
('C-Class C300d', 'Mercedes-Benz', '2024', 'Premium', 'Diesel', 'Automatic', 5200.0, 'Available', 'mercedes.jpg'),
('E-Class E350d', 'Mercedes-Benz', '2024', 'Premium', 'Diesel', 'Automatic', 6800.0, 'Available', 'mercedes.jpg'),
('3 Series GL', 'BMW', '2024', 'Premium', 'Petrol', 'Automatic', 4800.0, 'Available', 'bmw.jpg'),
('5 Series 530d', 'BMW', '2024', 'Premium', 'Diesel', 'Automatic', 6000.0, 'Available', 'bmw.jpg'),
('7 Series 740i', 'BMW', '2024', 'Premium', 'Petrol', 'Automatic', 9500.0, 'Available', 'bmw.jpg'),
('X3 xDrive20d', 'BMW', '2023', 'Premium', 'Diesel', 'Automatic', 5200.0, 'Available', 'bmw.jpg'),
('X5 xDrive30d', 'BMW', '2023', 'Premium', 'Diesel', 'Automatic', 7500.0, 'Available', 'bmw.jpg'),
('X7 xDrive40i', 'BMW', '2024', 'Premium', 'Petrol', 'Automatic', 9800.0, 'Available', 'bmw.jpg'),
('3 Series 330i', 'BMW', '2023', 'Premium', 'Petrol', 'Automatic', 4600.0, 'Available', 'bmw.jpg'),
('5 Series 520d', 'BMW', '2024', 'Premium', 'Diesel', 'Automatic', 5800.0, 'Available', 'bmw.jpg'),
('A4 40 TFSI', 'Audi', '2024', 'Premium', 'Petrol', 'Automatic', 4000.0, 'Available', 'audi.jpg'),
('A6 45 TFSI', 'Audi', '2024', 'Premium', 'Petrol', 'Automatic', 5200.0, 'Available', 'audi.jpg'),
('A8 L 55 TFSI', 'Audi', '2024', 'Premium', 'Petrol', 'Automatic', 8800.0, 'Available', 'audi.jpg'),
('Q3 40 TFSI', 'Audi', '2023', 'Premium', 'Petrol', 'Automatic', 4200.0, 'Available', 'audi.jpg'),
('Q5 45 TFSI', 'Audi', '2023', 'Premium', 'Petrol', 'Automatic', 5500.0, 'Available', 'audi.jpg'),
('Q7 55 TFSI', 'Audi', '2024', 'Premium', 'Petrol', 'Automatic', 7200.0, 'Available', 'audi.jpg'),
('A6 2.0 TDI', 'Audi', '2023', 'Premium', 'Diesel', 'Automatic', 5000.0, 'Available', 'audi.jpg'),
('Q5 2.0 TDI', 'Audi', '2023', 'Premium', 'Diesel', 'Automatic', 5400.0, 'Available', 'audi.jpg'),
('Velar Diesel', 'Land Rover', '2024', 'Premium', 'Diesel', 'Automatic', 8000.0, 'Available', 'range_rover.png'),
('Range Rover Sport', 'Land Rover', '2024', 'Premium', 'Diesel', 'Automatic', 10000.0, 'Available', 'range_rover.png'),
('Evoque Petrol', 'Land Rover', '2023', 'Premium', 'Petrol', 'Automatic', 6000.0, 'Available', 'range_rover.png'),
('Defender 110', 'Land Rover', '2024', 'Premium', 'Diesel', 'Automatic', 9000.0, 'Available', 'range_rover.png'),
('Range Rover Vogue', 'Land Rover', '2024', 'Premium', 'Diesel', 'Automatic', 15000.0, 'Available', 'range_rover.png'),
('Discovery Diesel', 'Land Rover', '2024', 'Premium', 'Diesel', 'Automatic', 7500.0, 'Available', 'range_rover.png'),
('Fortuner 4x4', 'Toyota', '2023', 'SUV', 'Diesel', 'Automatic', 4000.0, 'Available', 'fortuner.jpg'),
('Fortuner Legender', 'Toyota', '2024', 'SUV', 'Diesel', 'Automatic', 4500.0, 'Available', 'fortuner.jpg'),
('Fortuner 4x2 MT', 'Toyota', '2023', 'SUV', 'Petrol', 'Manual', 3500.0, 'Available', 'fortuner.jpg'),
('Fortuner GR Sport', 'Toyota', '2024', 'SUV', 'Diesel', 'Automatic', 4800.0, 'Available', 'fortuner.jpg'),
('Thar LX Diesel AT', 'Mahindra', '2023', 'SUV', 'Diesel', 'Automatic', 3000.0, 'Available', 'thar.jpg'),
('Thar AX Opt Petrol MT', 'Mahindra', '2023', 'SUV', 'Petrol', 'Manual', 2500.0, 'Available', 'thar.jpg'),
('Thar Earth Edition', 'Mahindra', '2024', 'SUV', 'Petrol', 'Automatic', 3200.0, 'Available', 'thar.jpg'),
('Thar RWD Diesel MT', 'Mahindra', '2023', 'SUV', 'Diesel', 'Manual', 2200.0, 'Available', 'thar.jpg'),
('Scorpio-N Z8L Diesel', 'Mahindra', '2024', 'SUV', 'Diesel', 'Automatic', 2800.0, 'Available', 'scorpio.jpg'),
('Scorpio-N Z6 Diesel MT', 'Mahindra', '2023', 'SUV', 'Diesel', 'Manual', 2200.0, 'Available', 'scorpio.jpg'),
('Scorpio-N Z4 Petrol MT', 'Mahindra', '2023', 'SUV', 'Petrol', 'Manual', 2000.0, 'Available', 'scorpio.jpg'),
('Scorpio Classic S11', 'Mahindra', '2024', 'SUV', 'Diesel', 'Manual', 2400.0, 'Available', 'scorpio.jpg'),
('XUV700 AX7L Petrol AT', 'Mahindra', '2024', 'SUV', 'Petrol', 'Automatic', 3500.0, 'Available', 'xuv700.jpg'),
('XUV700 AX5 Diesel MT', 'Mahindra', '2023', 'SUV', 'Diesel', 'Manual', 2800.0, 'Available', 'xuv700.jpg'),
('XUV700 AX3 Petrol MT', 'Mahindra', '2023', 'SUV', 'Petrol', 'Manual', 2200.0, 'Available', 'xuv700.jpg'),
('XUV700 AX7 Diesel AT', 'Mahindra', '2024', 'SUV', 'Diesel', 'Automatic', 3300.0, 'Available', 'xuv700.jpg'),
('Creta SX Petrol CVT', 'Hyundai', '2024', 'SUV', 'Petrol', 'Automatic', 2000.0, 'Available', 'creta.jpg'),
('Creta SX(O) Diesel AT', 'Hyundai', '2024', 'SUV', 'Diesel', 'Automatic', 2200.0, 'Available', 'creta.jpg'),
('Creta Knight Edition', 'Hyundai', '2023', 'SUV', 'Petrol', 'Manual', 1800.0, 'Available', 'creta.jpg'),
('Creta E Diesel MT', 'Hyundai', '2023', 'SUV', 'Diesel', 'Manual', 1500.0, 'Available', 'creta.jpg'),
('Seltos GTX+ Diesel AT', 'Kia', '2024', 'SUV', 'Diesel', 'Automatic', 2100.0, 'Available', 'seltos.jpg'),
('Seltos X-Line Petrol DCT', 'Kia', '2024', 'SUV', 'Petrol', 'Automatic', 2300.0, 'Available', 'seltos.jpg'),
('Seltos HTX Petrol MT', 'Kia', '2023', 'SUV', 'Petrol', 'Manual', 1800.0, 'Available', 'seltos.jpg'),
('Harrier Fearless+ AT', 'Tata', '2024', 'SUV', 'Diesel', 'Automatic', 3200.0, 'Available', 'harrier.jpg'),
('Harrier Adventure MT', 'Tata', '2023', 'SUV', 'Diesel', 'Manual', 2600.0, 'Available', 'harrier.jpg'),
('Harrier Pure+ MT', 'Tata', '2023', 'SUV', 'Diesel', 'Manual', 2200.0, 'Available', 'harrier.jpg'),
('Venue SX Petrol iMT', 'Hyundai', '2023', 'SUV', 'Petrol', 'Automatic', 1600.0, 'Available', 'venue.jpg'),
('Venue N Line N8', 'Hyundai', '2024', 'SUV', 'Petrol', 'Automatic', 1800.0, 'Available', 'venue.jpg'),
('Innova Crysta 2.4 VX', 'Toyota', '2023', 'SUV', 'Diesel', 'Manual', 3000.0, 'Available', 'innova.jpg'),
('Innova Hycross Hybrid', 'Toyota', '2024', 'SUV', 'Petrol', 'Automatic', 3500.0, 'Available', 'innova.jpg'),
('Nexon EV Max XZ+', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 2200.0, 'Available', 'nexon.jpg'),
('Nexon EV Prime XM', 'Tata', '2023', 'Electric', 'Electric', 'Automatic', 1800.0, 'Available', 'nexon.jpg'),
('Nexon EV Empowered+', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 2400.0, 'Available', 'nexon.jpg'),
('Nexon EV Fearless+', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 2000.0, 'Available', 'nexon.jpg'),
('Nexon EV Creative+', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 1700.0, 'Available', 'nexon.jpg'),
('Punch EV Empowered+', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 1600.0, 'Available', 'punch.jpg'),
('Punch EV Adventure', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 1400.0, 'Available', 'punch.jpg'),
('Punch EV Smart', 'Tata', '2024', 'Electric', 'Electric', 'Automatic', 1300.0, 'Available', 'punch.jpg'),
('e-tron 55 Quattro', 'Audi', '2024', 'Electric', 'Electric', 'Automatic', 9000.0, 'Available', 'audi.jpg'),
('e-tron Sportback 55', 'Audi', '2024', 'Electric', 'Electric', 'Automatic', 9500.0, 'Available', 'audi.jpg'),
('e-tron GT Coupe', 'Audi', '2023', 'Electric', 'Electric', 'Automatic', 12000.0, 'Available', 'audi.jpg'),
('Q8 e-tron 50', 'Audi', '2024', 'Electric', 'Electric', 'Automatic', 8500.0, 'Available', 'audi.jpg'),
('i4 eDrive40 Sedan', 'BMW', '2024', 'Electric', 'Electric', 'Automatic', 6000.0, 'Available', 'bmw.jpg'),
('iX xDrive50 SUV', 'BMW', '2024', 'Electric', 'Electric', 'Automatic', 8500.0, 'Available', 'bmw.jpg'),
('i7 xDrive60 Luxury', 'BMW', '2024', 'Electric', 'Electric', 'Automatic', 11000.0, 'Available', 'bmw.jpg'),
('iX1 xDrive30 Sport', 'BMW', '2024', 'Electric', 'Electric', 'Automatic', 5500.0, 'Available', 'bmw.jpg'),
('EQS 580 4MATIC', 'Mercedes-Benz', '2024', 'Electric', 'Electric', 'Automatic', 11000.0, 'Available', 'mercedes.jpg'),
('EQB 300 SUV', 'Mercedes-Benz', '2023', 'Electric', 'Electric', 'Automatic', 5000.0, 'Available', 'mercedes.jpg'),
('EQE 500 SUV', 'Mercedes-Benz', '2024', 'Electric', 'Electric', 'Automatic', 7800.0, 'Available', 'mercedes.jpg'),
('EQS AMG 53', 'Mercedes-Benz', '2024', 'Electric', 'Electric', 'Automatic', 13000.0, 'Available', 'mercedes.jpg'),
('ZS EV Exclusive+', 'MG', '2024', 'Electric', 'Electric', 'Automatic', 2100.0, 'Available', 'nexon.jpg'),
('Atto 3 Superior', 'BYD', '2024', 'Electric', 'Electric', 'Automatic', 2300.0, 'Available', 'nexon.jpg'),
('Seal Performance AWD', 'BYD', '2024', 'Electric', 'Electric', 'Automatic', 3800.0, 'Available', 'verna.jpg'),
('Ioniq 5 AWD', 'Hyundai', '2023', 'Electric', 'Electric', 'Automatic', 3500.0, 'Available', 'creta.jpg'),
('EV6 GT-Line AWD', 'Kia', '2024', 'Electric', 'Electric', 'Automatic', 4200.0, 'Available', 'seltos.jpg'),
('XUV400 EV EL Pro', 'Mahindra', '2024', 'Electric', 'Electric', 'Automatic', 1800.0, 'Available', 'xuv700.jpg'),
('Tiago EV Lux', 'Tata', '2023', 'Electric', 'Electric', 'Automatic', 1100.0, 'Available', 'swift.jpg'),
('Tigor EV XZ+', 'Tata', '2023', 'Electric', 'Electric', 'Automatic', 1200.0, 'Available', 'verna.jpg'),
('Comet EV Plush', 'MG', '2024', 'Electric', 'Electric', 'Automatic', 900.0, 'Available', 'punch.jpg'),
('XC40 Recharge SUV', 'Volvo', '2024', 'Electric', 'Electric', 'Automatic', 5500.0, 'Available', 'xuv700.jpg'),
('Swift ZXI+ Petrol MT', 'Maruti Suzuki', '2024', 'Budget', 'Petrol', 'Manual', 1200.0, 'Available', 'swift.jpg'),
('Swift VXI Petrol MT', 'Maruti Suzuki', '2023', 'Budget', 'Petrol', 'Manual', 1000.0, 'Available', 'swift.jpg'),
('Swift ZXI+ Petrol AT', 'Maruti Suzuki', '2024', 'Budget', 'Petrol', 'Automatic', 1300.0, 'Available', 'swift.jpg'),
('Swift LXI MT', 'Maruti Suzuki', '2023', 'Budget', 'Petrol', 'Manual', 900.0, 'Available', 'swift.jpg'),
('Baleno Alpha Petrol AGS', 'Maruti Suzuki', '2024', 'Budget', 'Petrol', 'Automatic', 1300.0, 'Available', 'baleno.jpg'),
('Baleno Delta Petrol MT', 'Maruti Suzuki', '2023', 'Budget', 'Petrol', 'Manual', 1100.0, 'Available', 'baleno.jpg'),
('Baleno Zeta CNG MT', 'Maruti Suzuki', '2024', 'Budget', 'Petrol', 'Manual', 1250.0, 'Available', 'baleno.jpg'),
('Amaze VX Petrol CVT', 'Honda', '2024', 'Budget', 'Petrol', 'Automatic', 1300.0, 'Available', 'amaze.jpg'),
('Amaze S Petrol MT', 'Honda', '2023', 'Budget', 'Petrol', 'Manual', 1000.0, 'Available', 'amaze.jpg'),
('Amaze VX Diesel MT', 'Honda', '2023', 'Budget', 'Diesel', 'Manual', 1200.0, 'Available', 'amaze.jpg'),
('Punch Creative Petrol MT', 'Tata', '2024', 'Budget', 'Petrol', 'Manual', 1100.0, 'Available', 'punch.jpg'),
('Punch Adventure AMT', 'Tata', '2023', 'Budget', 'Petrol', 'Automatic', 1200.0, 'Available', 'punch.jpg'),
('Punch Accomplished CNG', 'Tata', '2024', 'Budget', 'Petrol', 'Manual', 1150.0, 'Available', 'punch.jpg'),
('City ZX Petrol CVT', 'Honda', '2024', 'Budget', 'Petrol', 'Automatic', 1800.0, 'Available', 'city.jpg'),
('City VX Petrol MT', 'Honda', '2023', 'Budget', 'Petrol', 'Manual', 1500.0, 'Available', 'city.jpg'),
('City V Diesel MT', 'Honda', '2023', 'Budget', 'Diesel', 'Manual', 1600.0, 'Available', 'city.jpg'),
('Verna SX(O) Turbo DCT', 'Hyundai', '2024', 'Budget', 'Petrol', 'Automatic', 2000.0, 'Available', 'verna.jpg'),
('Verna SX Petrol MT', 'Hyundai', '2024', 'Budget', 'Petrol', 'Manual', 1600.0, 'Available', 'verna.jpg'),
('Verna S Diesel MT', 'Hyundai', '2023', 'Budget', 'Diesel', 'Manual', 1500.0, 'Available', 'verna.jpg'),
('i20 N Line N8 DCT', 'Hyundai', '2024', 'Budget', 'Petrol', 'Automatic', 1600.0, 'Available', 'i20.jpg'),
('i20 Asta Petrol IVT', 'Hyundai', '2024', 'Budget', 'Petrol', 'Automatic', 1400.0, 'Available', 'i20.jpg'),
('i20 Sportz Diesel MT', 'Hyundai', '2023', 'Budget', 'Diesel', 'Manual', 1200.0, 'Available', 'i20.jpg'),
('WagonR ZXI Petrol MT', 'Maruti Suzuki', '2023', 'Budget', 'Petrol', 'Manual', 900.0, 'Available', 'swift.jpg'),
('Alto K10 Petrol MT', 'Maruti Suzuki', '2023', 'Budget', 'Petrol', 'Manual', 700.0, 'Available', 'swift.jpg'),
('Dzire ZXI Petrol MT', 'Maruti Suzuki', '2023', 'Budget', 'Petrol', 'Manual', 1100.0, 'Available', 'city.jpg'),
('i10 Nios Asta Petrol MT', 'Hyundai', '2023', 'Budget', 'Petrol', 'Manual', 1000.0, 'Available', 'i20.jpg'),
('Kwid Climber Petrol MT', 'Renault', '2023', 'Budget', 'Petrol', 'Manual', 800.0, 'Available', 'swift.jpg'),
('Tiago XZ+ Petrol MT', 'Tata', '2023', 'Budget', 'Petrol', 'Manual', 950.0, 'Available', 'punch.jpg'),
('Slavia Style Petrol AT', 'Skoda', '2023', 'Budget', 'Petrol', 'Automatic', 1900.0, 'Available', 'verna.jpg'),
('Virtus GT Petrol DSG', 'Volkswagen', '2024', 'Budget', 'Petrol', 'Automatic', 2100.0, 'Available', 'verna.jpg');

-- Insert a Demo Admin Account (password is 'admin123')
INSERT INTO users (name, email, password, phone, role) VALUES
('System Administrator', 'admin@carrental.com', 'admin123', '+1 (800) 555-0100', 'admin');
